sudo: required

dist: trusty

language: python

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      services:
        - docker
      env:
        - JOB=lint
      env:
        - JOB=test_py3_lint
        - IMG=tensorflow/tensorflow
      install:
        - docker pull $IMG
      script:
        - docker run -t --rm -v `pwd`:/root/lbn -w /root/lbn $IMG bash -c "pip install flake8; flake8 lbn.py test.py setup.py"

    - stage: test
      services:
        - docker
      env:
        - JOB=test_py2_tf1
        - IMG=tensorflow/tensorflow:1.15.2
      install:
        - docker pull $IMG
      script:
        - docker run -t --rm -v `pwd`:/root/lbn -w /root/lbn $IMG python -m unittest test

    - stage: test
      services:
        - docker
      env:
        - JOB=test_py3_tf1
        - IMG=tensorflow/tensorflow:1.15.2-py3
      install:
        - docker pull $IMG
      script:
        - docker run -t --rm -v `pwd`:/root/lbn -w /root/lbn $IMG python -m unittest test

    - stage: test
      services:
        - docker
      env:
        - JOB=test_py2_tf2
        - IMG=tensorflow/tensorflow:2.1.0
      install:
        - docker pull $IMG
      script:
        - docker run -t --rm -v `pwd`:/root/lbn -w /root/lbn $IMG python -m unittest test

    - stage: test
      services:
        - docker
      env:
        - JOB=test_py3_tf2
        - IMG=tensorflow/tensorflow:2.4.0
      install:
        - docker pull $IMG
      script:
        - docker run -t --rm -v `pwd`:/root/lbn -w /root/lbn $IMG python -m unittest test
